package reviewer

import (
	"context"
	"fmt"
	"strings"
	"time"

	sharedgithub "github.com/oyetanishq/yappr/apps/shared/github"
)

// CommentPoster formats the ReviewResult as GitHub-Flavored Markdown and posts
// (or updates) the PR comment via the GitHub API.
type CommentPoster struct {
	client *sharedgithub.Client
}

// NewCommentPoster creates a CommentPoster.
func NewCommentPoster(client *sharedgithub.Client) *CommentPoster {
	return &CommentPoster{client: client}
}

// Post replaces the "processing..." placeholder comment with the full review.
// If InitCommentID is 0, it posts a new comment instead.
func (p *CommentPoster) Post(ctx context.Context, req ReviewRequest, rc *ReviewContext, result *ReviewResult) error {
	body := p.format(req, rc, result)

	if req.InitCommentID != 0 {
		return p.client.UpdateComment(ctx, req.Repo, req.InitCommentID, req.InstallID, body)
	}
	_, err := p.client.PostComment(ctx, req.Repo, req.PRNumber, req.InstallID, body)
	return err
}

// PostError updates (or posts) a minimal error comment when the pipeline fails.
func (p *CommentPoster) PostError(ctx context.Context, req ReviewRequest, errMsg string) error {
	body := fmt.Sprintf("## 🤖 Yappr AI Code Review\n\n> ⚠️ **Review failed**: %s\n\nPlease check the agent logs or re-open the PR to retry.\n\n<sub>Generated by Yappr · %s</sub>",
		errMsg,
		time.Now().UTC().Format("2006-01-02 15:04 UTC"),
	)

	if req.InitCommentID != 0 {
		return p.client.UpdateComment(ctx, req.Repo, req.InitCommentID, req.InstallID, body)
	}
	_, err := p.client.PostComment(ctx, req.Repo, req.PRNumber, req.InstallID, body)
	return err
}

// format assembles the complete GitHub-Flavored Markdown comment body.
func (p *CommentPoster) format(req ReviewRequest, rc *ReviewContext, result *ReviewResult) string {
	var sb strings.Builder

	// ── Header ───────────────────────────────────────────────────────────
	sb.WriteString("## 🤖 Yappr AI Code Review\n\n")
	sb.WriteString(fmt.Sprintf(
		"> **PR #%d** · @%s · %d files · +%d -%d\n\n",
		req.PRNumber,
		req.Author,
		rc.FileCount,
		rc.TotalAdditions,
		rc.TotalDeletions,
	))
	sb.WriteString("---\n\n")

	// ── Section 1: PR Summary ─────────────────────────────────────────────
	sb.WriteString("## 📋 PR Summary\n\n")
	if result.Summary != "" {
		// Strip "## PR Summary" header if the model included it (avoid duplication)
		summary := strings.TrimPrefix(result.Summary, "## PR Summary")
		summary = strings.TrimSpace(summary)
		sb.WriteString(summary)
	} else {
		sb.WriteString("_Summary not available._")
	}
	sb.WriteString("\n\n---\n\n")

	// ── Section 2: Changed Files ──────────────────────────────────────────
	if result.FileChanges != "" {
		fileChanges := strings.TrimSpace(result.FileChanges)
		sb.WriteString(fileChanges)
		sb.WriteString("\n\n---\n\n")
	}

	// ── Section 3: Architecture Flow Diagram (Pro only — omit entirely when absent) ──
	if result.FlowDiagram != "" {
		sb.WriteString("## 🏗 Architecture Flow\n\n")
		diagram := extractMermaidBlock(result.FlowDiagram)
		if diagram != "" {
			sb.WriteString("```mermaid\n")
			sb.WriteString(diagram)
			sb.WriteString("\n```\n")
		} else {
			// the model returned a full mermaid block — use as-is
			sb.WriteString(result.FlowDiagram)
		}
		sb.WriteString("\n---\n\n")
	}

	// ── Section 4 & 5: Bug Report + Fixes ────────────────────────────────
	sb.WriteString("## 🐛 Bugs & Edge Cases Found\n\n")
	if result.BugReport != "" {
		bugReport := strings.TrimSpace(result.BugReport)
		sb.WriteString(bugReport)
	} else {
		sb.WriteString("_Bug analysis not available._")
	}
	sb.WriteString("\n\n---\n\n")

	// ── Analysis Stats ────────────────────────────────────────────────────
	sb.WriteString("<details>\n<summary>📊 Analysis Statistics</summary>\n\n")
	sb.WriteString("| Metric | Value |\n")
	sb.WriteString("|--------|-------|\n")
	sb.WriteString(fmt.Sprintf("| Files Changed | %d |\n", rc.FileCount))
	sb.WriteString("\n</details>\n\n")

	// ── Footer ───────────────────────────────────────────────────────────
	sb.WriteString(fmt.Sprintf(
		"<sub>🔍 Reviewed by Yappr AI · %s · [Report an issue](https://github.com/%s/issues)</sub>",
		time.Now().UTC().Format("2006-01-02 15:04 UTC"),
		req.Repo,
	))

	return sb.String()
}

// extractMermaidBlock strips the ```mermaid ... ``` wrapper if the model included it,
// returning just the raw diagram content. If no wrapper found, returns "".
func extractMermaidBlock(text string) string {
	text = strings.TrimSpace(text)
	// Look for ```mermaid ... ``` wrapper
	startMarker := "```mermaid"
	endMarker := "```"

	startIdx := strings.Index(text, startMarker)
	if startIdx < 0 {
		return "" // no wrapper found — caller will use raw text
	}
	content := text[startIdx+len(startMarker):]
	endIdx := strings.LastIndex(content, endMarker)
	if endIdx < 0 {
		return strings.TrimSpace(content)
	}
	return strings.TrimSpace(content[:endIdx])
}
